// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRwOzJOFUvHqMmUl0XZE9I1U0owNtgOjs',
    appId: '1:848251963424:web:652e1a34145ba973a05445',
    messagingSenderId: '848251963424',
    projectId: 'keep-fit-firebase',
    authDomain: 'keep-fit-firebase.firebaseapp.com',
    storageBucket: 'keep-fit-firebase.appspot.com',
    measurementId: 'G-710EVJ40M8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUsbdPLK-ScaIGUnGP9C7NNW0Im5qhxdA',
    appId: '1:848251963424:android:491e575da8472f46a05445',
    messagingSenderId: '848251963424',
    projectId: 'keep-fit-firebase',
    storageBucket: 'keep-fit-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQfO4wnR0LwXEzRB1fjdXpE5q07dazl-A',
    appId: '1:848251963424:ios:a998cf1526c343d8a05445',
    messagingSenderId: '848251963424',
    projectId: 'keep-fit-firebase',
    storageBucket: 'keep-fit-firebase.appspot.com',
    iosBundleId: 'com.example.keepFit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQfO4wnR0LwXEzRB1fjdXpE5q07dazl-A',
    appId: '1:848251963424:ios:a998cf1526c343d8a05445',
    messagingSenderId: '848251963424',
    projectId: 'keep-fit-firebase',
    storageBucket: 'keep-fit-firebase.appspot.com',
    iosBundleId: 'com.example.keepFit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRwOzJOFUvHqMmUl0XZE9I1U0owNtgOjs',
    appId: '1:848251963424:web:186727ffc38eea27a05445',
    messagingSenderId: '848251963424',
    projectId: 'keep-fit-firebase',
    authDomain: 'keep-fit-firebase.firebaseapp.com',
    storageBucket: 'keep-fit-firebase.appspot.com',
    measurementId: 'G-4BPJ4DGR78',
  );
}
